name: Scrape LeBonCoin de Theo

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Chrome 138
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7615.0/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          Xvfb :99 -ac &  # démarrage d’un affichage virtuel
          python app/scraper.py
